name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - doxygen
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: doxygen
          submodules: true

      - name: Build
        uses: mattnotmitt/doxygen-action@v1.9.2

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: docs/html

